### ISSUE TITLE
./ProgressBar not found in components

### ISSUE THREAD

**Issue by Slyracoon23** [citydaoproject/app#100]
## Issue
The react component file ProgressBar is not in the ~/src/components list
```
./src/components/index.ts
Module not found: Can't resolve './ProgressBar' in '/media/slyracoon23/Extreme SSD/Ubuntu-files/Documents/CityDao/parcel-viewer/app/packages/react-app/src/components'
```
Looking at the git-blame it looks like @gregfromstl committed the code 9 months ago

## Solution
Add the component 

## Tag
@gregfromstl @trkaplan

**Comment by Slyracoon23** [comment]
It looks fixed in one of the PRs

**Comment by trkaplan** [comment]
closing thanks!
