### ISSUE TITLE
use x0ABCD...EFGH format as wallet address

### ISSUE THREAD

**Issue by trkaplan** [citydaoproject/app#107]
When displaying wallet addresses use this format. 
There seems to be two places where we display those addresses:
Top right, when connected wallet. This format looks OK but It does not show the right digits as I see.
 
The other one:
NFT holder address on the right panel.
<img width="237" alt="image" src="https://user-images.githubusercontent.com/992897/177219721-1026b0f8-928b-4607-87f0-54bdbc69242a.png">

**Comment by blackeagle0188** [comment]
> When displaying wallet addresses use this format. There seems to be two places where we display those addresses: Top right, when connected wallet. This format looks OK but It does not show the right digits as I see.
> 
> The other one: NFT holder address on the right panel. <img alt="image" width="237" src="https://user-images.githubusercontent.com/992897/177219721-1026b0f8-928b-4607-87f0-54bdbc69242a.png">

![image](https://user-images.githubusercontent.com/68125284/177226231-1de57f7d-def5-4e51-a48e-5a377813fa1d.png)
It looks like this one.

**Comment by trkaplan** [comment]
Address format on the plot details panel is fixed thank you. 
But when wallet is connected, the format looks OK but digits are wrong. Can you check this? 
And the error message also has this wrong digit problem .
<img width="298" alt="image" src="https://user-images.githubusercontent.com/992897/177433741-fd9d3836-fae4-44c8-98bf-fac4fae7b473.png">
<img width="266" alt="image" src="https://user-images.githubusercontent.com/992897/177433832-ba051d8e-bf20-4c75-bd52-d1bc9bb455c1.png">

**Comment by blackeagle0188** [comment]
> Address format on the plot details panel is fixed thank you. But when wallet is connected, the format looks OK but digits are wrong. Can you check this? And the error message also has this wrong digit problem . <img alt="image" width="298" src="https://user-images.githubusercontent.com/992897/177433741-fd9d3836-fae4-44c8-98bf-fac4fae7b473.png"> <img alt="image" width="266" src="https://user-images.githubusercontent.com/992897/177433832-ba051d8e-bf20-4c75-bd52-d1bc9bb455c1.png">

How about these?
![image](https://user-images.githubusercontent.com/68125284/177477267-38d71f16-91bb-42bf-8741-eba0fca41037.png)
![image](https://user-images.githubusercontent.com/68125284/177477309-470edcd3-719b-46c7-aef9-b7a62a9a6f65.png)

**Comment by trkaplan** [comment]
fixed with #114 closing. Don't forget to pull latest main branch
