### ISSUE TITLE
paste issue on search input

### ISSUE THREAD

**Issue by trkaplan** [citydaoproject/app#108]
When pasting a plot number, If the cursor is at the end of the input box, it just appends the pasted number to the current one.
When pasting a plot number It should just replace the input with the first 4 chars of the pasted value. 
ie.
value in Search Box is: 0000 and cursor position at 4th char.
pasting 1234 should replace input with 1234, no regards where cursors position is located.

**Comment by blackeagle0188** [comment]
> 

It has fixed.
[https://app-6eujxk2oo-citydao.vercel.app/](https://app-6eujxk2oo-citydao.vercel.app/)

**Comment by trkaplan** [comment]
Fixed here 84a3e14178689031e3d3f001526df4c23422e205 Thank you!
