### ISSUE TITLE
List owned Parcel-0 NFTs when wallet is connected

### ISSUE THREAD

**Issue by trkaplan** [citydaoproject/app#110]
When I connect my wallet which includes Parcel-0 NFT(s) I want to see my NFTs on the **Your Plots** tab. 
Now it displays an error even I have the Parcel-0 NFT in my wallet. 
Here is the contract API:
https://etherscan.io/address/0x90384e76b6b3ddb47396ff85144819ded148900d#readProxyContract 
You can get help on using the API from @mdnorman, reveal team.  or @Slyracoon23

in the UI; 
"Your Plots" link is clickable and will display the list of plots when clicked. 
If user searches a plot or clicks on a plot on the map, your Plots list will gone. 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/992897/177436974-11d8c5b3-af1b-4b23-a22f-0b2ce098c341.png">
I'll ask Casey to make this tab button more visible

**Comment by Slyracoon23** [comment]
I am slowing reviewing my code on my side. I will see if I can reproduce your problem.

**Comment by trkaplan** [comment]
Hey thanks for quick comment Earl! 
It is not a bug actually, It has not been implemented yet with current Parcel-0 contract.

**Comment by trkaplan** [comment]
It displays an notification after I close It my parcel-0 NFTs becomes visible. Can you check it?
![image](https://user-images.githubusercontent.com/992897/177629920-211271a2-d662-424b-b4dc-9fcaaddc1f0a.png)

**Comment by Slyracoon23** [comment]
I think I know the issue. @trkaplan are you saying you are getting the Toast even though you have an Parcel-0 NFT.

I believe it is happening here
src/views/BrowsePlots.tsx
```
useEffect(() => {
    if (!userAddress) {
      return;
    }
    debugger;
    if (whitelistedAmount && whitelistedAmount > 0) {
      toast.dismiss("notWhitelisted");
      toast.success(`You've been whitelisted to buy ${whitelistedAmount} plots 🎉`, {
        toastId: "isWhitelisted",
        autoClose: false,
      });
    } else {
      toast.dismiss("isWhitelisted");
      toast.error(
        "You don’t own a Parcel-0 NFT in your wallet: " + userAddress?.slice(0, 6) + "..." + userAddress?.slice(-5, -1),
        {
          toastId: "notWhitelisted",
          autoClose: false,
        },
      );
    }
  }, [whitelistedAmount, userAddress]);
```
The reason why it's failing I think is because after `userAddress` has been updated it will re-render. However I don't believe the `whitelistedAmount` has updated before the `userAddress `hence causing the error.

You can see later that where `whitelistedAmount` is used and set
```
 useEffect(() => {
    readWhitelistStatus();
  }, [contracts, userAddress, plots]);
```

# Solution
 We can either change the dependencies of the useEffect for the Toast update to only update for `whitelistedAmount`
OR
We can have the `readWhitelistStatus()` useEffect ordered first before the Toast useEffect()

According to React docs
*React will apply every effect used by the component, in the order they were specified.*

I believe it will apply for re-renders too

**Comment by blackeagle0188** [comment]
> I think I know the issue. @trkaplan are you saying you are getting the Toast even though you have an Parcel-0 NFT.
> 
> I believe it is happening here src/views/BrowsePlots.tsx
> 
> ```
> useEffect(() => {
>     if (!userAddress) {
>       return;
>     }
>     debugger;
>     if (whitelistedAmount && whitelistedAmount > 0) {
>       toast.dismiss("notWhitelisted");
>       toast.success(`You've been whitelisted to buy ${whitelistedAmount} plots 🎉`, {
>         toastId: "isWhitelisted",
>         autoClose: false,
>       });
>     } else {
>       toast.dismiss("isWhitelisted");
>       toast.error(
>         "You don’t own a Parcel-0 NFT in your wallet: " + userAddress?.slice(0, 6) + "..." + userAddress?.slice(-5, -1),
>         {
>           toastId: "notWhitelisted",
>           autoClose: false,
>         },
>       );
>     }
>   }, [whitelistedAmount, userAddress]);
> ```
> 
> The reason why it's failing I think is because after `userAddress` has been updated it will re-render. However I don't believe the `whitelistedAmount` has updated before the `userAddress `hence causing the error.
> 
> You can see later that where `whitelistedAmount` is used and set
> 
> ```
>  useEffect(() => {
>     readWhitelistStatus();
>   }, [contracts, userAddress, plots]);
> ```
> 
> # Solution
> We can either change the dependencies of the useEffect for the Toast update to only update for `whitelistedAmount` OR We can have the `readWhitelistStatus()` useEffect ordered first before the Toast useEffect()
> 
> According to React docs _React will apply every effect used by the component, in the order they were specified._
> 
> I believe it will apply for re-renders too

Yeah. I have already fixed it yesterday :)
