### ISSUE TITLE
fix Parcel-0 text and remove space in mobile view + remove whitelist link

### ISSUE THREAD

**Issue by trkaplan** [citydaoproject/app#118]
1- Set PARCEL 0 titles font to a smaller one on mobile to make it fit in one line. 
2- Remove unwanted space under header bar. 
3- Clicking logo and parcel-0 text redirects to /whitelist link. Remove this link.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/992897/178260970-6fecb26a-186b-4ee1-bb72-f90868af3e48.png">

**Comment by trkaplan** [comment]
@blackeagle0188  can you check 2 and 3, if you have time before me? 
Solution for 1:
replace `text-lg` in `LogoDisplay.tsx` with `md:text-xl` to fix Parcel-0 title size.

**Comment by blackeagle0188** [comment]
> 1- Set PARCEL 0 titles font to a smaller one on mobile to make it fit in one line. 2- Remove unwanted space under header bar. 3- Clicking logo and parcel-0 text redirects to /whitelist link. Remove this link.
> 
> <img alt="image" width="480" src="https://user-images.githubusercontent.com/992897/178260970-6fecb26a-186b-4ee1-bb72-f90868af3e48.png">

fixed all issues and created PR

**Comment by trkaplan** [comment]
Thank you @blackeagle0188
